name: JetBrains Tests
on:
  pull_request:
jobs:
  test:
    name: JetBrains tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - run: yarn global add pnpm@8.6.7
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: Run Tests
        run: ./gradlew --stacktrace --info test
      - name: Run Build Plugin
        run: ./gradlew --info buildPlugin
      - name: Check formatting
        run: ./gradlew spotlessCheck
