name: Semgrep - SAST Scan

on: [pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      - name: Checkout semgrep-rules repo
        uses: actions/checkout@v3
        with:
          repository: sourcegraph/security-semgrep-rules
          token: ${{ secrets.GH_SEMGREP_SAST_TOKEN }}
          path: semgrep-rules

      - name: Run Semgrep SAST Scan
        run: |
          semgrep ci -f semgrep-rules/ --metrics=off --oss-only --suppress-errors --sarif -o results.sarif --exclude='semgrep-rules'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
