name: vscode-nightly

on:
  schedule:
    - cron: '0 15 * * *' # daily at 1500 UTC
  workflow_dispatch:

jobs:
  release:
    if: github.ref == 'refs/heads/main' && github.repository == 'sourcegraph/cody'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - run: vscode/scripts/download-rg.sh x86_64-unknown-linux
      - run: xvfb-run -a pnpm run test
      - run: CODY_RELEASE_TYPE=nightly pnpm -C vscode run release
        if: github.ref == 'refs/heads/main' && github.repository == 'sourcegraph/cody'
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          VSCODE_OPENVSX_TOKEN: ${{ secrets.VSCODE_OPENVSX_TOKEN }}
